services:

  postgres:
    image: postgres:17
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/wallet_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data: